version: '2'
services:
    tomato:
        image: quay.io/alileza/tomato:latest
        volumes:
          - src:/src
        command:
          - "--config.file=/src/tomato.yml"
          - "--features.path=/src/features/"
        environment:
            CLIENT_BASE_URL: "http://sample-app:9000"
            DATABASE_DSN: "postgres://sample-app:sample-password@postgres:5432/sample-app?sslmode=disable"
            QUEUE_DSN: "amqp://guest:guest@rabbitmq:5672"
            CUSTOMER_APP_PORT: 8880

    sample-app:
        build: .
        expose:
            - "9000"
        environment:
            DATABASE_DSN: "postgres://sample-app:sample-password@postgres:5432/sample-app?sslmode=disable"
            QUEUE_DSN: "amqp://guest:guest@rabbitmq:5672"
            CUSTOMER_APP_BASE_URL: "http://tomato:8880"
        entrypoint: >
          sh -c '/util/waitfor postgres:5432 rabbitmq:5672 && sample-app'
        volumes:
          - util:/util
          - src:/src
          - sqldump:/src/migrations

    postgres:
        image: postgres:9.5
        expose:
            - "5432"
        environment:
            POSTGRES_USER: sample-app
            POSTGRES_PASSWORD: sample-password
            POSTGRES_DB: sample-app
        volumes:
          - sqldump:/docker-entrypoint-initdb.d/

    rabbitmq:
        image: rabbitmq:3.6.1-management
        expose:
            - "5672"


    waitfor:
      image: alileza/waitfor:latest
      volumes:
        - util:/bin/
      entrypoint: [ "tail", "-f", "/dev/null" ]

volumes:
  util: {}
  src: {}
  sqldump: {}
